export const routes = {
  home: "/",
  shop: "/shop",
  products: "/products",
  brands: "/brands",
  showrooms: "/showrooms",
  about: "/about",
  contact: "/contact",
  blog: "/blog",
  help: "/help",
  privacy: "/privacy",
  terms: "/terms",
  login: "/auth/login",
  signup: "/auth/sign-up",
};
